# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d09c77c140d81679c443e62736c470a2a01cd7603056cba4c331a4436a9ccc1b1376fe39a4296ead4e878df4e1acb8543ad0fc1e3449c2414b016da427408d6a

test:
  secret_key_base: 7a56cb233c43d90d9bb37d2a93d90c1824de2f1f47f74bed2380fb858ac4de0ef1bcb0ea317b12dbb0181efcdfe56cccd7b030d771c250653432553fccbb03f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
